segmentio:
  host: "localhost"
  port: "9992"
  secure: true
  skip_verify: true
  topic: "segmentio_topic"
  auto_create_topic: false
  forwarder:
    produce_messages: false
    messages_count: 1
  getter:
    consume_messages: true
    group_id: "consumer_group_id"
    commit_messages: true

log_level: "info"
